name: Deploy-Nexus

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: epirartifact
        path: tartget/epir.war
        
        
