name: test

on: 
  [push]

jobs: 
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo-a-string
        run: echo "Welcome to github actions"
      - name: working-dir
        run: pwd
      - name: multi-line
        run: |
          echo $SHELL
          pwd
          whoami
          java --version
  windows-test:
    needs: run-shell-commands
    runs-on: windows-latest
    steps:
      - name: create-a-folder
        run: md folder1
      - name: name-and-list
        run: |
          md folder2
          ls
          rm folder1
          ls
  third-test:
    needs: [ run-shell-commands, windows-test ]
    runs-on: ubuntu-latest
    steps:
      - name: test-cmd
        run: "echo third job"
      
